### ISSUE TITLE
Deployment in AWS Amplify

### ISSUE THREAD

**Issue by jerriclynsjohn** [Elderjs/elderjs#162]
I've been using Netlify for our website using Elder.js, we were able to successfully run builds there by just adding a `.nvmrc` file with our latest version `v14.15.1`. This made deployment a breeze with Netlify. Now I'm trying to do the same in AWS Amplify and with literally no success till now. Would highly appreciate it if there are any best practices steps that I have to follow while deploying to AWS Amplify. This is the settings that I use now

```yaml
version: 1
frontend:
  phases:
    build:
      commands:
        - nvm install 14.15.1
        - npm i --production=false && npm run build
  artifacts:
    baseDirectory: public
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
